repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.23.1
    hooks:
    - id: django-upgrade
      args: [--target-version, "4.2"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    - id: pyupgrade
      args: [--py39-plus]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions==3.14.0
