# Generated by Django 2.1.5 on 2019-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180628_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.book',),
        ),
        migrations.AddField(
            model_name='book',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
