# Generated by Django 2.2.7 on 2021-05-02 07:46
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_auto_20211111_0807"),
    ]

    operations = [
        migrations.CreateModel(
            name="UUIDBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, default=uuid.uuid4, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Book name")),
            ],
        ),
    ]
