# Generated by Django 4.0.4 on 2022-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_uuidcategory_legacybook_alter_uuidbook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
