# Generated by Django 4.2.3 on 2023-09-15 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_uuidcategory_legacybook_alter_uuidbook_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyBook",
        ),
    ]
