# Generated by Django 5.0.3 on 2024-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_uuidcategory_legacybook_alter_uuidbook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Time published'),
        ),
    ]
