# Generated by Django 4.2.3 on 2023-10-11 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_delete_legacybook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birthday",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
