# Generated by Django 5.0.4 on 2024-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_bookwithchapternumbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithPositiveIntegerFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("big", models.PositiveBigIntegerField(null=True)),
                ("small", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
