# Generated by Django 5.0.4 on 2024-05-18 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_withpositiveintegerfields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="uuidcategory",
            options={"verbose_name_plural": "UUID categories"},
        ),
    ]
