# Generated by Django 5.0.4 on 2024-05-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_category_options_alter_uuidcategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NamedAuthor",
            fields=[
                (
                    "name",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="uuidbook",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.namedauthor",
            ),
        ),
    ]
