# Generated by Django 5.0 on 2025-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_namedauthor_uuidbook_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="resource",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
